name: Build Project

on:
 workflow_dispatch:
 release:
  types: [ published ]
 push:
  branches: [ main ]

permissions:
 contents: write

jobs:
 build:
  runs-on: windows-latest
  steps:
  - uses: actions/checkout@v4.1.4
  - name: Setup MSBuild
    uses: microsoft/setup-msbuild@v2
  - name: Setup NuGet
    uses: NuGet/setup-nuget@v2.0.0
  - name: Restore Packages
    run: nuget restore MergeSort.sln
  - name: Build solution
    run: msbuild MergeSort.sln -t:rebuild -property:Configuration=Release
  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
     name: Release
     path: MergeSort\bin\Release
     if-no-files-found: error
 release:
  runs-on: ubuntu-latest
  needs: build
  if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
  steps:
  - run: mkdir Release-MergeSort
  - uses: actions/download-artifact@v4
    with:
     name: Release
     path: Release-MergeSort
  - run: zip Release.zip Release-MergeSort -r
  - name: Upload Release Asset
    uses: actions/upload-release-asset@v1
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
     upload_url: ${{ github.event.release.upload_url }}
     asset_content_type: application/zip
     asset_name: Release-MergeSort.zip
     asset_path: Release.zip
